"""
growthlens.backtest.real_run
============================
Runs the real-data backtest end-to-end: load hand-collected CSV -> score with
the actual model -> join real outcomes -> metrics -> honest report.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

import pandas as pd

from growthlens import config as C
from growthlens.cleaning.normalize import clean_companies
from growthlens.scoring.ge_readiness import score_companies
from growthlens.backtest.real import load_real_csv, observed_pillars_note
from growthlens.backtest.metrics import (
    base_rate, precision_curve, rank_auc, decile_lift,
)

REAL_DIR = C.DATA_DIR / "real"
REPORT_DIR = C.PROCESSED_DIR / "backtest"


def run_real_backtest(csv_path: str | Path, ks: list[int] | None = None) -> dict:
    """Score a hand-collected CSV against real outcomes and write a report."""
    cfg = C.load_scoring_config()
    df, coverage = load_real_csv(csv_path)

    n = len(df)
    ks = ks or [k for k in (5, 10, 20, 50) if k <= n]

    clean = clean_companies(df)
    scored = score_companies(clean, cfg)

    outcome_by_id = dict(zip(df["company_id"], df["raised_within_12m"]))
    scored = scored.assign(
        raised_within_12m=scored["company_id"].map(outcome_by_id)
    ).dropna(subset=["raised_within_12m"])
    scored = scored.sort_values("ge_readiness_score", ascending=False).reset_index(drop=True)
    sorted_outcomes = scored["raised_within_12m"].astype(int)

    results = {
        "n": int(len(scored)),
        "base_rate": round(base_rate(sorted_outcomes), 3),
        "auc": round(rank_auc(scored["ge_readiness_score"], sorted_outcomes), 3),
        "curve": precision_curve(sorted_outcomes, ks),
        "deciles": decile_lift(sorted_outcomes) if len(scored) >= 10 else None,
        "coverage": coverage,
        "coverage_note": observed_pillars_note(coverage),
    }
    results["report_path"] = _write_real_report(results)
    return results


def _write_real_report(results: dict, out_dir: Path = REPORT_DIR) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    br, auc, n = results["base_rate"], results["auc"], results["n"]

    lines = [
        f"# GrowthLens — REAL-DATA backtest · {date.today().isoformat()}",
        "",
        "> Real companies, real hand-collected outcomes. The model ran on the "
        "subset of features observable from free public sources; unobservable "
        "features were neutrally imputed and contribute **nothing** to the "
        "ranking. Read the coverage section before quoting any number.",
        "",
        "## Headline",
        f"- Companies with a recorded outcome: **{n}**",
        f"- Base rate: **{br:.1%}** raised within 12 months of the cutoff",
        f"- Rank AUC: **{auc:.3f}** (0.5 = random)",
        "",
        "## Observability coverage",
        f"{results['coverage_note']}",
        "",
        "| Feature | Observed in % of rows |",
        "|---|---:|",
    ]
    for feat, cov in sorted(results["coverage"].items(), key=lambda x: -x[1]):
        lines.append(f"| {feat} | {cov:.0%} |")

    lines += ["", "## Precision@K", "", "| K | precision@K | lift@K |", "|---:|---:|---:|"]
    for _, r in results["curve"].iterrows():
        lines.append(f"| {int(r['K'])} | {r['precision_at_K']:.1%} | {r['lift_at_K']:.2f}× |")

    if results["deciles"] is not None:
        lines += ["", "## Decile lift", "", "| Decile | n | raise rate | lift |",
                  "|---:|---:|---:|---:|"]
        for _, r in results["deciles"].iterrows():
            lines.append(f"| {int(r['decile'])} | {int(r['n'])} | {r['raise_rate']:.1%} | {r['lift']:.2f}× |")

    lines += [
        "",
        "## How to read this honestly",
        f"- With **N = {n}**, every number has wide error bars. Treat this as "
        "directional evidence, not proof. More companies = tighter estimates.",
        "- The model is running **without its heaviest pillar** (revenue growth, "
        "unobservable here). AUC above 0.5 on observable features alone is a "
        "meaningful — and honestly bounded — result.",
        "- The gap between this AUC and the full-feature synthetic backtest is a "
        "direct estimate of *what the paid data buys you*.",
        "",
        "*Generated by growthlens.backtest.real_run. Re-run as you add companies.*",
    ]
    path = out_dir / f"real_backtest_{date.today().isoformat()}.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
